### ISSUE TITLE
Some questions to start using it

### ISSUE THREAD

**Issue by pierrocknroll** [tystuyfzand/websub-server#2]
Hi and thank you for your great job !

I have some questions about it :
- Your exemples are very light, is there something to do to have logs when a subscribe or a publish is made ?
- Is it possible to use a database like MySQL to store the subscribers ?
- Did you made the 5.3.1 part of the W3C article, where the hub must confirm a subscribe by receiving a GET request with the hub.challenge issued during the subscribe ? I can't make it work.
- The W3C article is not very clear about the parameters to send for publishing, do you use, in addition to hub.mode=publish, the parameter hub.topic or hub.url?
- I have an error when a subscribe request is made and a hub.lease_seconds param is send by the subscriber to the hub : 'hub.lease_seconds' expected type 'int', got unconvertible type '[]string', value: '[60]'

Thanks again !

**Comment by tystuyfzand** [comment]
1. See AddHandler and [events.go](https://github.com/tystuyfzand/websub-server/blob/ec6669679887082d02b9d450718e4e86a6435b1a/events.go) - you can add funcs which take these as the only argument and they'll be passed when something happens, meaning you can log anything you'd like. There's also the Validator which can verify it's a topic you handle.
2. Yes, see the `store` package. This is made specifically to allow something like MySQL, SQLite, etc to store records. Note that these aren't implemented by default as sqlite, at least, would require cgo to build and complicating the package more. Third party packages would be greatly appreciated for implementations of these.
3. Yep! They must validate with the hub.challenge, See [this code](https://github.com/tystuyfzand/websub-server/blob/main/hub.go#L328-L404) which handles verification of challenges against the endpoint. The subscriptions are not stored until verified.
4. The publishing spec is weird in general, but requires `hub.topic` to specify which topic it's updating. The ContentProvider type provides a way for the hub to retrieve content if you had something custom, or simply pass through data if you'd like it to. [The default](https://github.com/tystuyfzand/websub-server/blob/main/content.go#L15-L43) is to send an HTTP GET request to the topic url.
5. I'll look into this, seems to be a bug with the lease time. I added an override to the DecodeHook for strings, seems like I didn't add one for integers.

**Comment by tystuyfzand** [comment]
@pierrocknroll 

I've created a basic, albeit untested sql store. I'll likely test it this weekend, but figured I'd push it up into the [feature/mysql](https://github.com/tystuyfzand/websub-server/tree/feature/store-mysql) branch for now!

Edit: Tested (basic) sql store added to the main branch under store/database!

**Comment by pierrocknroll** [comment]
Thanks a lot, it's clear for me now :) :+1:
